import Link from "next/link";
import { unstable_noStore as noStore } from "next/cache";
import { notFound } from "next/navigation";

import { AppHeader } from "@/components/app-header";
import { SeriesCard } from "@/components/series-card";
import { StoryCard } from "@/components/story-card";
import { getServerSession } from "@/lib/session";
import { partitionStoriesIntoSeriesAndStandalone } from "@/lib/series";
import {
  getPublicAuthorProfile,
  listReadStoryIdsForUser,
} from "@/lib/story-service";
import { getViewCounts } from "@/lib/view-buffer";

type AuthorPageProps = {
  params: Promise<{
    userId: string;
  }>;
};

export async function generateMetadata({ params }: AuthorPageProps) {
  const { userId } = await params;
  const data = await getPublicAuthorProfile(userId);

  if (!data) {
    return {
      title: "Reader not found",
    };
  }

  return {
    title: `${data.user.name} · Public lessons | HanziLane`,
    description: `Read public Chinese lessons generated by ${data.user.name} on HanziLane.`,
  };
}

export default async function AuthorProfilePage({ params }: AuthorPageProps) {
  noStore();
  const { userId } = await params;
  const session = await getServerSession();
  const data = await getPublicAuthorProfile(userId);

  if (!data) {
    notFound();
  }

  const { user, stories } = data;
  const readStoryIds = session
    ? await listReadStoryIdsForUser(session.user.id)
    : [];

  const { series: authorSeries, standalone } =
    partitionStoriesIntoSeriesAndStandalone(stories);

  const storyViewCounts =
    stories.length > 0 ? await getViewCounts(stories.map((s) => s.id)) : new Map();

  const hasSeries = authorSeries.length > 0;
  const hasStandalone = standalone.length > 0;
  const hasAny = hasSeries || hasStandalone;

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_#fff8f5,_#f7f0e8_52%,_#f3ede4_100%)] text-[#202020]">
      <AppHeader active="library" />
      <div className="mx-auto w-full max-w-[1400px] px-4 py-8 sm:px-6 sm:py-10 xl:px-10">
        <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:gap-6">
          {user.image ? (
            <img
              src={user.image}
              alt=""
              className="size-16 shrink-0 rounded-full border border-[#eadcd2] bg-white object-cover shadow-sm sm:size-20"
            />
          ) : (
            <div className="flex size-16 shrink-0 items-center justify-center rounded-full border border-[#eadcd2] bg-[#fff3ef] text-xl font-semibold text-[#d14f43] sm:size-20 sm:text-2xl">
              {user.name.slice(0, 1).toUpperCase()}
            </div>
          )}
          <div className="min-w-0 space-y-2">
            <h1 className="text-2xl font-semibold tracking-tight text-[#241815] sm:text-3xl">
              {user.name}
            </h1>
            <p className="text-sm leading-6 text-[#6f625c]">
              Public lessons on HanziLane. Private lessons stay on the author&apos;s account only.
            </p>
            <Link
              href="/"
              prefetch={false}
              className="inline-flex text-sm font-medium text-[#c66052] underline-offset-2 hover:underline"
            >
              Back to library
            </Link>
          </div>
        </div>

        {!hasAny ? (
          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-[#241815] sm:text-xl">Public library</h2>
            <div className="rounded-[24px] border border-dashed border-[#e0d3ca] bg-white/80 px-6 py-12 text-center text-sm text-[#6f625c]">
              This reader hasn&apos;t published any public lessons yet.
            </div>
          </section>
        ) : (
          <div className="space-y-10">
            {hasSeries ? (
              <section className="space-y-3">
                <div className="space-y-1">
                  <h2 className="text-lg font-semibold tracking-tight text-[#271d18] sm:text-xl">
                    Public series
                  </h2>
                  <p className="text-xs leading-5 text-[#6d615b] sm:text-sm sm:leading-6">
                    Multi-episode collections. Open a card to read in order.
                  </p>
                </div>
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                  {authorSeries.map((entry) => {
                    const totalViews = entry.stories.reduce(
                      (sum, story) => sum + (storyViewCounts.get(story.id) ?? 0),
                      0,
                    );
                    return (
                      <SeriesCard
                        key={entry.slug}
                        series={entry}
                        readCount={
                          entry.stories.filter((story) => readStoryIds.includes(story.id)).length
                        }
                        totalViews={totalViews}
                      />
                    );
                  })}
                </div>
              </section>
            ) : null}

            {hasStandalone ? (
              <section className="space-y-3">
                <div className="space-y-1">
                  <h2 className="text-lg font-semibold tracking-tight text-[#271d18] sm:text-xl">
                    {hasSeries ? "Single lessons" : "Public lessons"}
                  </h2>
                  <p className="text-xs leading-5 text-[#6d615b] sm:text-sm sm:leading-6">
                    {hasSeries
                      ? "Stand-alone readings not part of a series above."
                      : "Individual lessons you can open directly."}
                  </p>
                </div>
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                  {standalone.map((story) => (
                    <StoryCard
                      key={story.id}
                      story={story}
                      showAuthor={false}
                      isRead={readStoryIds.includes(story.id)}
                      viewCount={storyViewCounts.get(story.id)}
                    />
                  ))}
                </div>
              </section>
            ) : null}
          </div>
        )}
      </div>
    </main>
  );
}
