import Link from "next/link";

export function AuthorAttribution({
  authorUserId,
  authorName,
  prefix = "Generated by ",
}: {
  authorUserId: string;
  authorName: string;
  prefix?: string;
}) {
  return (
    <p className="text-[0.82rem] leading-6 text-[#6e625c] sm:text-sm">
      <span className="text-[#9b8e87]">{prefix}</span>
      <Link
        href={`/authors/${authorUserId}`}
        prefetch={false}
        className="font-medium text-[#c66052] underline-offset-2 hover:underline"
      >
        {authorName}
      </Link>
    </p>
  );
}
